const SUPABASE_URL = "https://qcipfrgxgboqneuoudox.supabase.co";
const SUPABASE_KEY = "sb_publishable_bTT6HwOvpKy8yJkTKx9s9g_mo71CgX4";
const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY, { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false} });
const state={rows:[],filtered:[],session:null}; const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat("pl-PL"); const dateFmt=new Intl.DateTimeFormat("pl-PL",{dateStyle:"short",timeStyle:"short"});
function num(v){return Number(v||0)} function money(v){return fmt.format(num(v))}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function arr(v){if(Array.isArray(v))return v;if(typeof v==="string"){try{const x=JSON.parse(v);return Array.isArray(x)?x:[]}catch{}}return[]}
function tankName(t){if(typeof t==="string")return t;if(!t||typeof t!=="object")return String(t??"");return t.name||t.title||t.tank||t.label||t.id||JSON.stringify(t)}
function tankTier(t){if(!t||typeof t!=="object")return null;const n=Number(t.tier);return Number.isFinite(n)?n:null}
function time(v){return v?dateFmt.format(new Date(v)):"—"}
function showApp(session){state.session=session;$("loginScreen").classList.add("hidden");$("appShell").classList.remove("hidden");$("userEmail").textContent=session?.user?.email||""}
function showLogin(message=""){state.session=null;$("appShell").classList.add("hidden");$("loginScreen").classList.remove("hidden");$("loginStatus").textContent=message}
async function checkAuth(){const{data,error}=await sb.auth.getSession();if(error||!data.session){showLogin("");return}showApp(data.session);await load()}
async function login(email,password){$("loginStatus").textContent="Logowanie...";const{data,error}=await sb.auth.signInWithPassword({email,password});if(error){$("loginStatus").textContent="Błędny e-mail lub hasło.";return}showApp(data.session);await load()}
async function logout(){await sb.auth.signOut();$("modal").classList.add("hidden");showLogin("Wylogowano.")}
async function load(){$("status").textContent="Ładowanie bazy...";$("refreshBtn").disabled=true;try{const{data,error}=await sb.from("accounts").select("*").order("updated_at",{ascending:false});if(error)throw error;state.rows=data||[];updateStats();render();$("status").textContent=`Załadowano ${state.rows.length} ${state.rows.length===1?"konto":"kont"}.`}catch(e){console.error(e);$("status").textContent="Nie udało się pobrać danych z Supabase: "+(e.message||e)}finally{$("refreshBtn").disabled=false}}
function updateStats(){const rows=state.rows;$("totalCount").textContent=fmt.format(rows.length);const avg=rows.length?rows.reduce((s,r)=>s+num(r.winrate),0)/rows.length:0;$("avgWinrate").textContent=avg.toFixed(2)+"%";$("totalBattles").textContent=fmt.format(rows.reduce((s,r)=>s+num(r.battles),0));$("lastUpdate").textContent=rows[0]?.updated_at?time(rows[0].updated_at):"—"}
function render(){const q=$("search").value.trim().toLowerCase(),sort=$("sort").value,premium=$("premiumOnly").checked;let rows=state.rows.filter(r=>{if(premium&&!r.premium_account)return false;if(!q)return true;const hay=[r.listing_id,r.clan,...arr(r.top_tanks).map(tankName),...arr(r.premium_tanks).map(tankName)].join(" ").toLowerCase();return hay.includes(q)});rows.sort((a,b)=>{if(sort==="winrate_desc")return num(b.winrate)-num(a.winrate);if(sort==="battles_desc")return num(b.battles)-num(a.battles);if(sort==="credits_desc")return num(b.credits)-num(a.credits);if(sort==="gold_desc")return num(b.gold)-num(a.gold);if(sort==="tanks_desc")return num(b.all_count)-num(a.all_count);return new Date(b.updated_at)-new Date(a.updated_at)});state.filtered=rows;$("grid").innerHTML=rows.map(card).join("");$("empty").classList.toggle("hidden",rows.length!==0)}
function card(r){const premium=!!r.premium_account;return `<article class="card" data-id="${esc(r.listing_id)}"><div class="card-head"><div><div class="id">#${esc(r.listing_id)}</div><div class="updated">Aktualizacja: ${esc(time(r.updated_at))}</div></div><span class="badge ${premium?"":"off"}">${premium?"PREMIUM":"STANDARD"}</span></div><div class="metrics"><div class="metric"><small>WINRATE</small><b>${num(r.winrate).toFixed(2)}%</b></div><div class="metric"><small>BITWY</small><b>${money(r.battles)}</b></div><div class="metric"><small>WYGRANE</small><b>${money(r.wins)}</b></div></div><div class="row"><span>Złoto</span><b>${money(r.gold)}</b></div><div class="row"><span>Kredyty</span><b>${money(r.credits)}</b></div><div class="row"><span>Klan</span><b>${esc(r.clan||"Brak")}</b></div><div class="tanks">Czołgi: <b>${money(r.all_count)}</b> · X: <b>${money(r.top_count)}</b> · Premium: <b>${money(r.premium_count)}</b></div></article>`}
function tankGroupsByTier(tanks){const groups=new Map();for(const t of tanks){const tier=tankTier(t),key=tier??0;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(t)}return[...groups.entries()].sort((a,b)=>b[0]-a[0])}
function tankGroupsHtml(tanks){if(!tanks.length)return"<span class='tank'>Brak danych</span>";return tankGroupsByTier(tanks).map(([tier,list])=>`<div class="tier-group">${tier?`<div class="tier-title">Poziom ${tier}</div>`:""}<div class="tank-list">${list.map(t=>`<span class="tank">${esc(tankName(t))}</span>`).join("")}</div></div>`).join("")}
async function deleteAccount(id){if(!window.confirm(`Usunąć konto #${id} z bazy?\n\nTej operacji nie można cofnąć.`))return;$("deleteBtn").disabled=true;$("deleteBtn").textContent="Usuwanie...";const{error}=await sb.from("accounts").delete().eq("listing_id",String(id));if(error){$("deleteBtn").disabled=false;$("deleteBtn").textContent="Usuń z bazy";$("deleteStatus").textContent="Nie udało się usunąć: "+error.message;return}state.rows=state.rows.filter(x=>String(x.listing_id)!==String(id));$("modal").classList.add("hidden");updateStats();render();$("status").textContent=`Usunięto konto #${id} z bazy.`}
function openDetails(id){const r=state.rows.find(x=>String(x.listing_id)===String(id));if(!r)return;const top=arr(r.top_tanks),prem=arr(r.premium_tanks);$("modalContent").innerHTML=`<h2 class="detail-title">Konto #${esc(r.listing_id)}</h2><div class="detail-sub">Ostatnia aktualizacja: ${esc(time(r.updated_at))}</div><div class="detail-actions"><a class="btn" href="https://lzt.market/${encodeURIComponent(r.listing_id)}/" target="_blank" rel="noopener">Otwórz ogłoszenie LZT ↗</a><button id="deleteBtn" class="btn danger">Usuń z bazy</button></div><div id="deleteStatus" class="delete-status"></div><div class="detail-grid"><div class="detail-box"><small>WINRATE</small><b>${num(r.winrate).toFixed(2)}%</b></div><div class="detail-box"><small>BITWY</small><b>${money(r.battles)}</b></div><div class="detail-box"><small>WYGRANE</small><b>${money(r.wins)}</b></div><div class="detail-box"><small>ZŁOTO</small><b>${money(r.gold)}</b></div><div class="detail-box"><small>KREDYTY</small><b>${money(r.credits)}</b></div><div class="detail-box"><small>KLAN</small><b>${esc(r.clan||"Brak")}</b></div><div class="detail-box"><small>PREMIUM</small><b>${r.premium_account?"Tak":"Nie"}</b></div><div class="detail-box"><small>WSZYSTKIE CZOŁGI</small><b>${money(r.all_count)}</b></div></div><div class="section"><h3>Czołgi X poziomu (${money(r.top_count)})</h3>${tankGroupsHtml(top)}</div><div class="section"><h3>Czołgi premium (${money(r.premium_count)})</h3>${tankGroupsHtml(prem)}</div><div class="section"><h3>Dane techniczne</h3><pre class="json">${esc(JSON.stringify(r,null,2))}</pre></div>`; $("deleteBtn").addEventListener("click",()=>deleteAccount(r.listing_id));$("modal").classList.remove("hidden")}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();await login($("loginEmail").value.trim(),$("loginPassword").value)});$("logoutBtn").addEventListener("click",logout);$("refreshBtn").addEventListener("click",load);$("search").addEventListener("input",render);$("sort").addEventListener("change",render);$("premiumOnly").addEventListener("change",render);$("grid").addEventListener("click",e=>{const c=e.target.closest(".card");if(c)openDetails(c.dataset.id)});$("closeModal").addEventListener("click",()=>$("modal").classList.add("hidden"));$("modalBackdrop").addEventListener("click",()=>$("modal").classList.add("hidden"));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("modal").classList.add("hidden")});
sb.auth.onAuthStateChange((event,session)=>{if(session){showApp(session);if(event==="SIGNED_IN")load()}else showLogin("")});checkAuth();